"""NiFi debugging runbook helpers (schema → HITL)."""

from ratatoskr.nifi.runbook.context import (
    allowed_remediation,
    constrain_remediation,
    enrich_monitor_context,
    order_refs,
    proposed_heal_plan,
    severity_guidance,
)
from ratatoskr.nifi.runbook.demo import (
    RUNBOOK_BRIEF_TOPIC,
    SCENARIOS,
    filter_ops_by_scenario,
    format_apply_status,
    list_scenarios,
    names_to_regex,
    operator_talking_points,
    publish_runbook_brief,
    run_offline_scenario,
    scenario_heal_regex,
    scenario_watch_regex,
    scoped_nifi_env,
    summarize_monitor,
    summarize_runbook,
)
from ratatoskr.nifi.runbook.fallback import fallback_runbook
from ratatoskr.nifi.runbook.fixtures import (
    FIXTURE_PACKS,
    list_fixture_ids,
    load_fixture,
)
from ratatoskr.nifi.runbook.hitl import (
    ACK_TOPIC,
    PROPOSE_TOPIC,
    apply_approved_heal,
    attach_hitl,
    build_heal_proposal,
    decide_approval,
    prompt_approve,
    publish_ack,
    publish_proposal,
)
from ratatoskr.nifi.runbook.schema import (
    RUNBOOK_SCHEMA_VERSION,
    empty_runbook,
    is_valid_runbook,
    is_valid_runbook_event,
    validate_runbook,
    validate_runbook_event,
    wrap_runbook_event,
)

__all__ = [
    "ACK_TOPIC",
    "FIXTURE_PACKS",
    "PROPOSE_TOPIC",
    "RUNBOOK_BRIEF_TOPIC",
    "RUNBOOK_SCHEMA_VERSION",
    "SCENARIOS",
    "allowed_remediation",
    "apply_approved_heal",
    "attach_hitl",
    "build_heal_proposal",
    "constrain_remediation",
    "decide_approval",
    "empty_runbook",
    "enrich_monitor_context",
    "fallback_runbook",
    "is_valid_runbook",
    "is_valid_runbook_event",
    "filter_ops_by_scenario",
    "format_apply_status",
    "list_fixture_ids",
    "list_scenarios",
    "load_fixture",
    "names_to_regex",
    "operator_talking_points",
    "order_refs",
    "prompt_approve",
    "proposed_heal_plan",
    "publish_ack",
    "publish_proposal",
    "publish_runbook_brief",
    "run_offline_scenario",
    "scenario_heal_regex",
    "scenario_watch_regex",
    "scoped_nifi_env",
    "severity_guidance",
    "summarize_monitor",
    "summarize_runbook",
    "validate_runbook",
    "validate_runbook_event",
    "wrap_runbook_event",
]
